import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const OPENAGENT_EXPERIMENTAL = truthy("OPENAGENT_EXPERIMENTAL")
const OPENAGENT_DISABLE_CLAUDE_CODE = truthy("OPENAGENT_DISABLE_CLAUDE_CODE")
const copy = process.env["OPENAGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENAGENT_AUTO_HEAP_SNAPSHOT: truthy("OPENAGENT_AUTO_HEAP_SNAPSHOT"),
  OPENAGENT_GIT_BASH_PATH: process.env["OPENAGENT_GIT_BASH_PATH"],
  OPENAGENT_CONFIG: process.env["OPENAGENT_CONFIG"],
  OPENAGENT_CONFIG_CONTENT: process.env["OPENAGENT_CONFIG_CONTENT"],
  OPENAGENT_DISABLE_AUTOUPDATE: truthy("OPENAGENT_DISABLE_AUTOUPDATE"),
  OPENAGENT_ALWAYS_NOTIFY_UPDATE: truthy("OPENAGENT_ALWAYS_NOTIFY_UPDATE"),
  OPENAGENT_DISABLE_PRUNE: truthy("OPENAGENT_DISABLE_PRUNE"),
  OPENAGENT_DISABLE_TERMINAL_TITLE: truthy("OPENAGENT_DISABLE_TERMINAL_TITLE"),
  OPENAGENT_SHOW_TTFD: truthy("OPENAGENT_SHOW_TTFD"),
  OPENAGENT_PERMISSION: process.env["OPENAGENT_PERMISSION"],
  OPENAGENT_DISABLE_DEFAULT_PLUGINS: truthy("OPENAGENT_DISABLE_DEFAULT_PLUGINS"),
  OPENAGENT_DISABLE_LSP_DOWNLOAD: truthy("OPENAGENT_DISABLE_LSP_DOWNLOAD"),
  OPENAGENT_DISABLE_AUTOCOMPACT: truthy("OPENAGENT_DISABLE_AUTOCOMPACT"),
  OPENAGENT_DISABLE_MODELS_FETCH: truthy("OPENAGENT_DISABLE_MODELS_FETCH"),
  OPENAGENT_DISABLE_MOUSE: truthy("OPENAGENT_DISABLE_MOUSE"),
  OPENAGENT_DISABLE_CLAUDE_CODE,
  OPENAGENT_DISABLE_CLAUDE_CODE_PROMPT: OPENAGENT_DISABLE_CLAUDE_CODE || truthy("OPENAGENT_DISABLE_CLAUDE_CODE_PROMPT"),
  OPENAGENT_DISABLE_EXTERNAL_SKILLS: truthy("OPENAGENT_DISABLE_EXTERNAL_SKILLS"),
  OPENAGENT_FAKE_VCS: process.env["OPENAGENT_FAKE_VCS"],
  OPENAGENT_SERVER_PASSWORD: process.env["OPENAGENT_SERVER_PASSWORD"],
  OPENAGENT_SERVER_USERNAME: process.env["OPENAGENT_SERVER_USERNAME"],
  OPENAGENT_ENABLE_QUESTION_TOOL: truthy("OPENAGENT_ENABLE_QUESTION_TOOL"),

  // Experimental
  OPENAGENT_EXPERIMENTAL,
  OPENAGENT_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENAGENT_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENAGENT_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENAGENT_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENAGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OPENAGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENAGENT_ENABLE_EXA: truthy("OPENAGENT_ENABLE_EXA") || OPENAGENT_EXPERIMENTAL || truthy("OPENAGENT_EXPERIMENTAL_EXA"),
  OPENAGENT_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("OPENAGENT_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  OPENAGENT_EXPERIMENTAL_LSP_TOOL: OPENAGENT_EXPERIMENTAL || truthy("OPENAGENT_EXPERIMENTAL_LSP_TOOL"),
  OPENAGENT_EXPERIMENTAL_PLAN_MODE: OPENAGENT_EXPERIMENTAL || truthy("OPENAGENT_EXPERIMENTAL_PLAN_MODE"),
  OPENAGENT_EXPERIMENTAL_SCOUT: OPENAGENT_EXPERIMENTAL || truthy("OPENAGENT_EXPERIMENTAL_SCOUT"),
  OPENAGENT_ENABLE_PARALLEL: truthy("OPENAGENT_ENABLE_PARALLEL") || truthy("OPENAGENT_EXPERIMENTAL_PARALLEL"),
  OPENAGENT_MODELS_URL: process.env["OPENAGENT_MODELS_URL"],
  OPENAGENT_MODELS_PATH: process.env["OPENAGENT_MODELS_PATH"],
  OPENAGENT_DB: process.env["OPENAGENT_DB"],
  OPENAGENT_SKIP_MIGRATIONS: truthy("OPENAGENT_SKIP_MIGRATIONS"),
  OPENAGENT_STRICT_CONFIG_DEPS: truthy("OPENAGENT_STRICT_CONFIG_DEPS"),

  OPENAGENT_WORKSPACE_ID: process.env["OPENAGENT_WORKSPACE_ID"],
  OPENAGENT_EXPERIMENTAL_WORKSPACES: OPENAGENT_EXPERIMENTAL || truthy("OPENAGENT_EXPERIMENTAL_WORKSPACES"),
  OPENAGENT_EXPERIMENTAL_EVENT_SYSTEM: OPENAGENT_EXPERIMENTAL || truthy("OPENAGENT_EXPERIMENTAL_EVENT_SYSTEM"),
  OPENAGENT_EXPERIMENTAL_SESSION_SWITCHING: OPENAGENT_EXPERIMENTAL || truthy("OPENAGENT_EXPERIMENTAL_SESSION_SWITCHING"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENAGENT_DISABLE_PROJECT_CONFIG() {
    return truthy("OPENAGENT_DISABLE_PROJECT_CONFIG")
  },
  get OPENAGENT_TUI_CONFIG() {
    return process.env["OPENAGENT_TUI_CONFIG"]
  },
  get OPENAGENT_CONFIG_DIR() {
    return process.env["OPENAGENT_CONFIG_DIR"]
  },
  get OPENAGENT_PURE() {
    return truthy("OPENAGENT_PURE")
  },
  get OPENAGENT_PLUGIN_META_FILE() {
    return process.env["OPENAGENT_PLUGIN_META_FILE"]
  },
  get OPENAGENT_CLIENT() {
    return process.env["OPENAGENT_CLIENT"] ?? "cli"
  },
}
